name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pipx
          pipx install poetry
          poetry install

      - name: "Run pre-commit tests"
        run: |
          poetry run python -m pre-commit install
          poetry run python -m pre-commit run --all-files
